import { expect, test } from "bun:test"

const Workflow = new URL("../.github/workflows/verify.yml", import.meta.url)
const ReleaseWorkflow = new URL("../.github/workflows/release.yml", import.meta.url)
const CodeqlWorkflow = new URL("../.github/workflows/codeql.yml", import.meta.url)
const SoakWorkflow = new URL("../.github/workflows/soak.yml", import.meta.url)
const Dependabot = new URL("../.github/dependabot.yml", import.meta.url)

test("hosted CI runs the complete pinned release gate and retains its evidence", async () => {
  const source = await Bun.file(Workflow).text()

  expect(() => Bun.YAML.parse(source)).not.toThrow()
  expect(source).toContain("permissions:\n  contents: read")
  expect(source).toContain("actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1")
  expect(source).toContain("oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0")
  expect(source).toContain("actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0")
  expect(source).toContain("node-version: 26.5.0")
  expect(source).toContain("denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5")
  expect(source).toContain("deno-version: 2.9.4")
  expect(source).toContain("bun install --frozen-lockfile")
  expect(source).toContain("run: bun run verify")
  expect(source).toContain(
    "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1"
  )
  expect(source).toContain("if: ${{ always() }}")
  expect(source).toContain("path: .artifacts/")
  expect(source).toContain("include-hidden-files: true")
})

test("manual release uses pinned tools OIDC provenance and no long-lived npm token", async () => {
  const source = await Bun.file(ReleaseWorkflow).text()
  expect(() => Bun.YAML.parse(source)).not.toThrow()
  expect(source).toContain("workflow_dispatch:")
  expect(source).toContain("environment: npm")
  expect(source).toContain("contents: read")
  expect(source).toContain("contents: write")
  expect(source).toContain("id-token: write")
  expect(source).toContain("bun-version: 1.3.14")
  expect(source).toContain("node-version: 26.5.0")
  expect(source).toContain("npm@12.0.1")
  expect(source).toContain("bun install --frozen-lockfile")
  expect(source).toContain("bun run verify")
  expect(source).toContain("changeset publish")
  expect(source).toContain("changeset tag")
  expect(source).toContain("push origin --follow-tags")
  expect(source).toContain("github-actions[bot]")
  expect(source).toContain("41898282+github-actions[bot]@users.noreply.github.com")
  expect(source).toContain("github.run_attempt")
  expect(source).toContain('test "$(git rev-parse HEAD)" = "$GITHUB_SHA"')
  expect(source).not.toContain("bun run build\n")
  expect(source.toLowerCase()).toContain("provenance")
  expect(source).toContain("group: release")
  expect(source).toContain("cancel-in-progress: false")
  expect(source).toContain("if: ${{ always() }}")
  expect(source).toContain("path: .artifacts/")
  expect(source).not.toContain("NODE_AUTH_TOKEN")
  expect(source).not.toContain("NPM_TOKEN")
  expect(source).not.toMatch(/uses:\s+[^\s@]+@v\d+/u)
})

test("CodeQL and Dependabot use pinned minimal JavaScript supply-chain configuration", async () => {
  const codeql = await Bun.file(CodeqlWorkflow).text()
  const dependabot = await Bun.file(Dependabot).text()
  expect(() => Bun.YAML.parse(codeql)).not.toThrow()
  expect(() => Bun.YAML.parse(dependabot)).not.toThrow()
  expect(codeql).toContain("languages: javascript-typescript")
  expect(codeql).toContain("security-events: write")
  expect(codeql).toContain(
    "github/codeql-action/init@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4.37.3"
  )
  expect(codeql).toContain(
    "github/codeql-action/analyze@e4fba868fa4b1b91e1fdab776edc8cfbe6e9fb81 # v4.37.3"
  )
  expect(codeql).not.toMatch(/uses:\s+[^\s@]+@v\d+/u)
  expect(dependabot).toContain('package-ecosystem: "npm"')
  expect(dependabot).toContain('package-ecosystem: "github-actions"')
})

test("hosted soak is scheduled and manual but never part of the pull request gate", async () => {
  const source = await Bun.file(SoakWorkflow).text()
  expect(() => Bun.YAML.parse(source)).not.toThrow()
  expect(source).toContain("workflow_dispatch:")
  expect(source).toContain("schedule:")
  expect(source).not.toContain("pull_request:")
  expect(source).toContain("timeout-minutes: 150")
  expect(source).toContain("bun-version: 1.3.14")
  expect(source).toContain("node-version: 26.5.0")
  expect(source).toContain("bun install --frozen-lockfile")
  expect(source).toContain("run: bun run soak:http")
  expect(source).toContain("run: bun run soak:check")
  expect(source).toContain("if: ${{ always() }}")
  expect(source).toContain("path: .artifacts/soak/")
  expect(source).not.toMatch(/uses:\s+[^\s@]+@v\d+/u)
})
