[test]
timeout = 10000
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = ["../context/**", "../core/**", "../registry/**", "test/**"]
coverageThreshold = { lines = 1.0, functions = 1.0 }
