[install]
exact = true

[test]
timeout = 10000
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coveragePathIgnorePatterns = ["**/dist/**", "**/test/**", "e2e/**", "examples/**"]
