[install]
exact = true

[test]
timeout = 10000
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coveragePathIgnorePatterns = [
  "**/dist/**",
  "**/test/**",
  "e2e/**",
  "examples/**",
  "scripts/soak.cli.ts",
  "scripts/published/**"
]
coverageThreshold = { functions = 1.0 }
