[test]
timeout = 10000
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = ".artifacts/coverage"
coveragePathIgnorePatterns = [
  "../../context/**",
  "../../core/**",
  "../src/**",
  "../../../tools/**",
  "test/**"
]
coverageThreshold = { functions = 1.0 }
