[test]
timeout = 10000
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = ".artifacts/coverage"
coveragePathIgnorePatterns = ["../web/**", "test/**"]
coverageThreshold = { lines = 1.0, functions = 1.0 }
