[test]
root = "test"
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = [
  "../broker/**",
  "../context/**",
  "../core/**",
  "../struct/**",
  "test/**"
]
coverageThreshold = { lines = 1.0, functions = 1.0 }
