[test]
timeout = 10000
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = [
  "../client/**",
  "../context/**",
  "../core/**",
  "../metadata/**",
  "../registry/**",
  "../resilience/**",
  "../transport/**",
  "test/**"
]
coverageThreshold = { lines = 1.0, functions = 1.0 }
