[test]
timeout = 10000
coverageSkipTestFiles = true
coveragePathIgnorePatterns = ["../context/**", "../registry/**", "test/**"]
coverageReporter = ["text", "lcov"]
coverageDir = ".artifacts/coverage"
coverageThreshold = { lines = 1.0, functions = 1.0 }
