[test]
root = "test"
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = ["../../context/**", "../../core/**", "../src/**", "test/**"]
coverageThreshold = { lines = 1.0, functions = 1.0 }
